### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by roelleor** [alexandrudima/typescript-with-globs#3]
Hi there, 
I was checking out this awesomeness, however when trying to execute tscg it gives the following error:
env: node\r: No such file or directory

My env: 
mac osx el capitan
tried with node 4, 5 and 6.

Thanks for any help!

**Comment by maybenull** [comment]
Linux Mint 17.2 Rafaela with commands

```
npm install typescript
npm install typescript-with-globs
npm run tsc  # run-script executes tscg with no args
```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/pettymt/.nvm/versions/node/v4.2.3/bin/node',
1 verbose cli   '/home/pettymt/.nvm/versions/node/v4.2.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'tsc' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose run-script [ 'pretsc', 'tsc', 'posttsc' ]
5 info pretsc sillyapp@1.0.0
6 info tsc sillyapp@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info sillyapp@1.0.0 Failed to exec tsc script
9 verbose stack Error: sillyapp@1.0.0 tsc: `tscg`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/home/pettymt/.nvm/versions/node/v4.2.3/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid sillyapp@1.0.0
11 verbose cwd /home/pettymt/Projects/somecompany/sillyapp
12 error Linux 3.16.0-38-generic
13 error argv "/home/pettymt/.nvm/versions/node/v4.2.3/bin/node" "/home/pettymt/.nvm/versions/node/v4.2.3/bin/npm" "run" "tsc"
14 error node v4.2.3
15 error npm  v2.14.7
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error sillyapp@1.0.0 tsc: `tscg`
20 error spawn ENOENT
21 error Failed at the sillyapp@1.0.0 tsc script 'tscg'.
21 error This is most likely a problem with the sillyapp package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     tscg
21 error You can get their info via:
21 error     npm owner ls sillyapp
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by wwwouter** [comment]
On my Chromebook/Ubuntu machine I had to change the CRLF to LF in the 'bin/tscg' file to make it work

**Comment by alexdima** [comment]
Archiving repo...
